### ISSUE TITLE
[BUG] setChildren with text 

### ISSUE THREAD

**Issue by mstip** [redom/redom#100]
Hi,

i think i found a bug in the latest version (3.10.2).

In Version 3.8.8 setChildren with a text node worked:

```
const {mount, el, text, setChildren} = redom;  
const app = document.getElementById('app');  
const myParagraph = el('p', 'text');  
mount(app, myParagraph);  
setChildren(myParagraph, [el('strong', 'title'), text('text')]);  
```
This results in 
```
<p><strong>title</strong>text</p>
```

In the latest version the text node will be ignored.

Jsfiddle example to play with: [Example](https://jsfiddle.net/nbrunch/k8an1pqL/).

Cheers

Marc

Ps: Keep up the good work, i love redom ; )

**Comment by pakastin** [comment]
Whoops, I'll check that – thanks!

**Comment by pakastin** [comment]
Fixed and released (v3.10.3) – thank you so much for letting know!

**Comment by pakastin** [comment]
https://jsfiddle.net/k8an1pqL/1/

**Comment by mstip** [comment]
@pakastin wow this was a really fast fix.
Thank a lot 👍

**Comment by pakastin** [comment]
Btw. Welcome to gitter.im/redom/redom 😉
