### ISSUE TITLE
ListPool, Place and Router require View with constructor

### ISSUE THREAD

**Issue by czb** [redom/redom#105]
Is there any reason why `ListPool`, `Place` and `Router` require `view` to have a `constructor`? E.g. for `Router`:

```
this.view = View && new View(this.initData, data);
```

I would much prefer something like:

```
function isConstructor(obj) {
  return !!obj.prototype && !!obj.prototype.constructor.name;
}

this.view = isConstructor(View) ? new View(this.initData, data) : View;
```

That would give me freedom to pass HTML Node or an object with `el` or a class into Router, ListPool and Place.

Are there any implications that I am not aware of?

PS: I like the idea of simplicity so if I can, I try to avoid classes as these are complex.

PPS: These 3 places are the only places where RE:DOM requires existence of a `constructor` so I must ask why? ;)

PPS: We could go even further -> check if it has a constructor, if not check if it is a function, if not just leave it as is, else call constructor or function

**Comment by czb** [comment]
That's right. So `ListPool` might support `function` and `class` whereas `Router` and `Place` might support `function`, `class` and `any`.

Place:

```
const view = isConstructor(View) ? new View(this._initData) : (typeof View === 'function' ? View(this._initData) : View);
``` 

Router:

```
this.view = isConstructor(View) ? new View(this.initData, data) : (typeof View === 'function' ? View(this.initData, data) : View);
```

ListPool:

```
view = oldLookup[id] || isConstructor(View) ? new View(initData, item, i, data) : View(initData, item, i, data);

view = oldViews[i] || isConstructor(View) ? new View(initData, item, i, data) : View(initData, item, i, data);
```

Do you think it is something that you could / want to include into the library?

**Comment by pakastin** [comment]
Sounds good! Wanna make PR? 👍

**Comment by pakastin** [comment]
Decided to separate to separate libraries: https://github.com/redom/redom/pull/106#issuecomment-383593775

Closing now..
