### ISSUE TITLE
ES modules

### ISSUE THREAD

**Issue by notruth** [redom/redom#107]
At first, Thank You for a great job! <3

How do you look at the idea of adding native ES modules support to the source code? Browsers that support modules will also support full ES6 syntax(which is used in the source code).
It will look like [hyperHTML/esm](https://github.com/WebReflection/hyperHTML/tree/master/esm).

What is needed for this?
* Add `'*.js'` to all imports paths;
* Replace `module` field in a package.json with `src/index.js`(instead of dist version).

**Comment by pakastin** [comment]
Sounds good! However what's the benefit of having multiple imports vs. one bundled import, or <ES6 vs ES6? With development that makes sense, but in the production I'm not that sure.

Btw. you _can_ already use:
```
<script type="module">
import { el, mount } from 'https://redom.js.org/redom.es.js'; // or redom.es.min.js
</script>
```

**Comment by notruth** [comment]
I know;) thanks.
I also want to use ES6(original) syntax, but current ESM bundle containes ES5 syntax(it works, i know), and, most importantly, it's a bundle. I think, Native ES modules should not look like bundle:)
`HyperHTML` library also has CDN version with ES modules. [https://github.com/WebReflection/hyperHTML#installation](https://github.com/WebReflection/hyperHTML#installation)

ES modules works well in browsers. So the point is that: Make a bundle is the work of the bundlers (`webpack`, `rollup`, `parcel` etc.)

**Comment by pakastin** [comment]
Fair enough, I'll make the changes 😉👍

**Comment by notruth** [comment]
Oh, THANKS! <3
I can help if needed

**Comment by pakastin** [comment]
If you want a contribution, I'm happy to merge a PR 😉

**Comment by notruth** [comment]
Yeah, I'll make a PR today.

**Comment by pakastin** [comment]
Perfect, thank you! 👌

**Comment by notruth** [comment]
So, I've researched this question. And that's what I found:
* "jsnext:main" is deprecated in favor of "module" field.
   https://github.com/jsforum/jsforum/issues/5
* "module" field recommended using for the same output like "main"(bundle version) but with ES modules.
   https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

I think that it would be logical to specify the original(ES6 syntax) version in "module" field. Because your source code has full support from the browsers who support the ES modules and it doesn't use external dependencies.
But, there is one conflict: bundlers like `parcel` or `rollup` use "module" field for resolving dep.tree, and by default, developers turn off the external modules transpilation(with `babel` or smth). 

So, better solution(i think...):
* Rename `/src` dir with `/esm`(or smth like this) for better import semantics;
* Add `*.js` to all imports;
(the rest - leave as is)

And guys who want to import Native code, just use: 
```javascript
 import { el, mount } from 'redom/esm/index.js';
  // or
  import mount from 'redom/esm/mount.js';
```

What Do You think about this? (Thanks)

**Comment by pakastin** [comment]
Sounds good! 👍

- I use `.js` on imports nowadays, so it's a good change.
- I don't fully understand why should `src` changed to `esm` though.
- It's good to use the bundled version, since one might use RE:DOM with (for example) NO:DOM in server-side with node.js, and there might be some older versions which don't support every ES6 feature out there.

**Comment by pakastin** [comment]
I'm ok with `esm` 👍

**Comment by pakastin** [comment]
You still wanna do that PR? 🙂

**Comment by notruth** [comment]
I propose to suspend this problem until tomorrow 😅
I want to make another research tomorrow(more objective) 🤔

**Comment by pakastin** [comment]
No hurries mate 😎

**Comment by notruth** [comment]
That's what I think:
It will be good if we add '*.js' to all imports. And at your discretion - rename `/src` to `/{smth}`(another alternative is a `/lib`) 🙂

**Comment by pakastin** [comment]
`esm` is fine

**Comment by notruth** [comment]
Ok, cool. I'll soon make a PR.

**Comment by def14nt** [comment]
Why not just throw an `index.js` in the root directory that imports the index from `/src/`?

**Comment by pakastin** [comment]
That’s not issue, but how to access submodules under `src`. However don’t see that as an issue, since you can access them through index anyway.. 🤷‍♂️
