### ISSUE TITLE
Remove items from list

### ISSUE THREAD

**Issue by CodeGradox** [redom/redom#112]
I have a list of elements where each element contains a link. When the user clicks the link the element will be removed. Each element is created from dynamic data.

I tried to create a view using something like this:
```js
this.el = place(... this.close = el("a") ...);
var self = this;
this.close.onclick = function() {
    self.el.update(false);
}
```
The problem is when I mount the list of views. The elements are hidden and when I tried to use `this.el.update(true)` inside the view's `update` function I got an error.

What is the correct way to do this?
So far I have created an object to store each element. The `onclick` event finds its element in the object and umounts it.

**Comment by pakastin** [comment]
`Place` currently only work with Views: https://redom.js.org/documentation/#place

I'd recommend to use lists in this case or just set `this.el.style.display = 'none';` instead..

**Comment by CodeGradox** [comment]
Yeah, that would work.

Thanks for the fast reply, and thanks for this awesome library!

**Comment by pakastin** [comment]
Thanks, and no worries! ;)

p.s. join us @ gitter.im/redom/redom or @ [Slack](https://redom.js.org/documentation/#support-feedback)
