### ISSUE TITLE
v4

### ISSUE THREAD

**Issue by pakastin** [redom/redom#114]
v4 checklist:
- [ ] .js –> .mjs
- [ ] Create better middleware system
- [ ] Separate `list`, `listpool`, `place` and `router`
- [ ] Simplify test system
- [ ] Probably new websites, too
- [x] #104

**Comment by def14nt** [comment]
You could mega-simplify the tests by spreading the tests out in categories in different files; I'll rustle together a PR if I got time.

**Comment by pakastin** [comment]
Yeah, I’ve done just that with my new test runner:
https://github.com/pakastin/testicle/tree/master/src

Would be nice to use that here too, since having ES6 module support out-of-the-box simplifies testing so much.

**Comment by pakastin** [comment]
Name’s a joke btw, I’m thinking of a better name for the runner 😄
https://github.com/pakastin/testicle/issues/3

**Comment by def14nt** [comment]
Nice name, but would you recommend making the jump to `.mjs` files? I'm currently working in `.js` files, but I am interested in native node support.

Just waiting for ES6 support in Node. I can see Babel dying out, then.

My problem now is that (this is in my project) the browser AFAIK doesn't understand Node imports, because my plan is to allow in-browser testing with Mocha. I can see myself needing to hardcode the `node_modules` bit in :angry:

**Comment by pakastin** [comment]
In client-side I just bundle `mjs`’s with rollup..

Test library is called Teston now btw:
https://github.com/pakastin/teston 😎

**Comment by def14nt** [comment]
OMG that test runner is fast. If you add Mocha compatibility I'll switch over in a heartbeat.

**Comment by pakastin** [comment]
Well, it’s super lightweight: https://github.com/pakastin/teston/blob/master/src/test.mjs 😉

**Comment by def14nt** [comment]
I know, running the tests is amazingly quick. Might be all the Babel fat with my tests though, but Mocha always has felt slow. I think optimizing tests should involve a build cache, so if the file doesn't change, the compiled (hidden built versions of the source) files are used. This approach is used by Python, too.

**Comment by pakastin** [comment]
That is a good idea! It might actually be possible automatically with rollup somehow 🤔

That’s actually the first time I’ve ever created a test runner, and result after a single day of work, so it will evolve for sure 🙂

**Comment by def14nt** [comment]
@pakastin I've been thinking about examples. What about a NodeJS app that submits bogus data to the frontend, then RE:DOM is used to lay it out into the DOM?

**Comment by pakastin** [comment]
What kind of app could it be? 🤔

It’s always a pain to come up with interesting examples.. 😞

**Comment by sloschi** [comment]
How about https://github.com/gothinkster/realworld

**Comment by def14nt** [comment]
@sloschi Looks good, but I think a Medium clone is a bit overkill.

**Comment by def14nt** [comment]
@pakastin On another note, should we move this conversation elsewhere? Seeing as this is the roadmap. (p.s you can do a roadmap in the wiki for this project)
