### ISSUE TITLE
Patterns to deal with event delegation for many similar event handlers

### ISSUE THREAD

**Issue by mindreframer** [redom/redom#118]
Hallo @pakastin, thank for for Redom, I really like its simplicity! 

What are the best practices for dealing with lots similar Eventhandlers, eg. in a big table with edit buttons? 

Attaching handler to each button individually seems expensive, React has synthetic events that help to avoid memory leaks. 

Best, 
Roman

**Comment by pakastin** [comment]
Hi @mindreframer!

Memory leaks are not an issue, just make sure event handlers are in the same scope than components.

If you are worried about performance of creating / removing multiple event handlers (usually only when you have A LOT of nodes), you can register a single event handler to the table itself, and by using `e.target` you can detect where it came from:

```
table.onclick = (e) => {
  if (e.target.tagName === 'BUTTON') {
    console.log(e.target, 'is a button and was clicked');
  }
};
```

**Comment by pakastin** [comment]
The beauty of RE:DOM is that the above is just pure JavaScript, so you can just follow web standards.

**Comment by pakastin** [comment]
btw. You're welcome to join [gitter.im/redom/redom](https://gitter.im/redom/redom) – I'm happy to answer any questions about good practices etc 😉

**Comment by pakastin** [comment]
Closing now
