### ISSUE TITLE
Fragments

### ISSUE THREAD

**Issue by vp2177** [redom/redom#121]
Is it possible to create a component in, RE:DOM, that consists of two or more top-level elements?

```js
class AandB {
  constructor() {
    this.el = [el("element-a"), new ComponentB()];
```

These are called "fragment", "multi-root component", "containerless" etc in other frameworks.

**Comment by pakastin** [comment]
Currently no, what's the use case for that?

**Comment by vp2177** [comment]
The ability to abstract an arbitrary part of the DOM into a component, without needing a wrapper element. `display: contents` will make wrappers harmless, but is not widely supported yet.

Here is a [use case from the React docs](https://reactjs.org/docs/fragments.html#motivation), although this was supported before Fragments by just returning an array from `render()`.

**Comment by MrSorcus** [comment]
@pakastin I think that i talked with you about similar feature here https://github.com/redom/redom/issues/93

**Comment by pakastin** [comment]
It would break the basic ”rule”, that component is always just a regular DOM element..

It’s different with virtual DOM.

**Comment by MrSorcus** [comment]
It can't be an array of `regular DOM elements`? Or i don't understand something...

**Comment by def14nt** [comment]
Can we not be React fanboys btw

**Comment by pakastin** [comment]
There’s certain issues with that, for example if `list` had array of elements as root elements, which one is the parent of list items..?

**Comment by pakastin** [comment]
Haha @def14nt 😂

**Comment by MrSorcus** [comment]
> There’s certain issues with that, for example if `list` had array of elements as root elements, which one is the parent of list items..?

Can you show example, please?

**Comment by def14nt** [comment]
@pakastin what about another property for the parent node?

**Comment by vp2177** [comment]
Could the rule be extended, so that a component is either an `Element` or a `DocumentFragment` (what `document.createDocumentFragment()` returns)? It's not just a React concept 🐠

**Comment by def14nt** [comment]
@vp2177 oohhh native interop sounds lovely

**Comment by pakastin** [comment]
Fragment is just a temporary place, once you mount the fragment, it gets empty..

**Comment by pakastin** [comment]
This is currently not possible, because of the nature of document fragment

**Comment by aziis98** [comment]
I had a similar problem and came up with this

https://codepen.io/aziis98/pen/mggqJw?editors=0010
