### ISSUE TITLE
redom loop

### ISSUE THREAD

**Issue by valentinbdv** [redom/redom#127]
Hello,

I was wondering if there was an easy way to deal with loop while creating the DOM with RE:DOM? Because I didn't find any in the doc or here in the issues. 

So this is what I came up with if anybody is interested, guess this is improvable : 
``` 
let presetsList = [
  {
    id:'11111',
    image:'https://redom.js.org/img/logo.svg',
    name:'redom image'
  }
];

let container = el('div.siimple-menu',
  (() => {
    let arr = [];
    for (let i = 0; i < presetsList.length; i++) {
      arr.push(
        el('div.siimple-menu-item',
          el('img', {src:presetsList[i].image})
        )
      );
    }
    return arr;
  })()
);
```

Cheerz ;)

**Comment by leeoniya** [comment]
use [Array#map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

```js
let container = el('div.simple-menu', presetsList.map(p =>
  el('div.simple-menu-item',
    el('img', {src: p.image})
  )
));
```

**Comment by valentinbdv** [comment]
Oh yeah so much better and clean. Don't know why I haven't thought about it!

Maybe that would deserve to be in the documentation somewhere?

**Comment by leeoniya** [comment]
it's standard javascript, so not much reason to add it, imo.

**Comment by pakastin** [comment]
@valentinbdv could also try: https://redom.js.org/documentation/#lists 😉
