### ISSUE TITLE
Add no-module example in homepage

### ISSUE THREAD

**Issue by spapas** [redom/redom#128]
Since there's a number of browsers that don't support the JS module via script tag feature (https://caniuse.com/#feat=es6-module) I think it'd be nice if you also add a no-module example in the homepage so that the fact that the library works that way also is declared more explicitly. Something like this:

```
<div id='root'></div>
<script type="text/javascript" src='https://redom.js.org/redom.min.js'></script>
<script type="text/javascript" 
    redom.mount(document.getElementById('root'), redom.el('h1', 'Hello modules!') )
</script>
```

TIA

**Comment by pakastin** [comment]
That is the way `redom.min.js` works already. `redom.es.min.js` is for ES6 modules.

See the [documentation](https://redom.js.org/documentation/#umd) and http://jsfiddle.net/hxk7vso6/

**Comment by spapas** [comment]
Yes I am aware of that, I just recommend to ad that to the home page to better advertise it; this is very useful!

**Comment by pakastin** [comment]
Yeah, good idea! 👍 Want to create PR?
