### ISSUE TITLE
Composing components

### ISSUE THREAD

**Issue by tobireif** [redom/redom#134]
This is is more of a question that an issue report.

How to compose components using RE:DOM?

What would be the RE:DOM equivalent of this?
```
<SomeComponent>
  <SomeOtherComponent/>
  <YetAnotherComponent/>
</SomeComponent>
```

**Comment by githingeorge** [comment]
```
el(SomeComponent, SomeOtherComponent, YetAnotherComponent)
```

**Comment by pakastin** [comment]
Yeah just pass children to component’s constructor/factory and inside constructor/factory to `el` arguments. You can do `el(query, ...children)` or `el(query, children)` whichever you find more practical..

**Comment by tobireif** [comment]
Thanks! Perhaps you want to add a small section eg "Composing Components" to https://redom.js.org/ .

**Comment by pakastin** [comment]
Good idea! Want to make a PR? 😎
