### ISSUE TITLE
Two ways of setting class names are mutually exclusive

### ISSUE THREAD

**Issue by jung-kurt** [redom/redom#136]
Class names can be set either with the shorthand form
```javascript
el('span.hello')
```
or the object form
```javascript
el('span', { class: 'hello' })
```
However, the object form overwrites the shortcut form:
```javascript
el('span.hello', { class: 'goodbye' }) // el.getAttribute('class') === 'goodbye'
```
I've got a case in which the object assignment is used programmatically and it would be useful for it not to interfere with the shorthand class assignment. In the `setAttr()` function, if
```javascript
el.setAttribute(arg1, arg2);
```
is replaced with
```javascript
if (arg1 === 'class') {
  var oldClass = el.getAttribute('class');
  if (oldClass) {
    arg2 = oldClass + ' ' + arg2;
  }
}
el.setAttribute(arg1, arg2);
```
both methods can be used. Would this be accepted as a pull request?

**Comment by pakastin** [comment]
I’ve actually thought about the same thing, but have to think about it a bit more.. I’ll get back to you tomorrow

**Comment by pakastin** [comment]
Didn't get back "tomorrow", sorry 😞

The problem with this is, that `setAttr` shouldn't always do it like that (if user uses the helper). I'll fix it to the element factory instead.

**Comment by jung-kurt** [comment]
Nice solution. Good work!

**Comment by pakastin** [comment]
Yeah, ended up creating internal helpers..
