### ISSUE TITLE
Document SVG "xlink:href" use

### ISSUE THREAD

**Issue by andrejcremoznik** [redom/redom#137]
I believe the pattern to use SVG symbols via `<svg><use xlink:href="#symbol"/></svg>` is common enough, that its usage should be documented in the official documentation. I had to STFW how to force the `xlink` namespace onto the `href` to find the solution [here](https://github.com/redom/redom/issues/94#issuecomment-346294572).

```js
svg('svg', svg('use', { xlink: { href: '#symbol' } }))
```

I wish all browsers would adhere to spec, but I'm pretty sure the `xlink:href` will remain backward compatible indefinitely.

**Comment by pakastin** [comment]
Oh yeah, sure! Want to make a PR?
