### ISSUE TITLE
Example for subclassing components?

### ISSUE THREAD

**Issue by acdha** [redom/redom#140]
I've been enjoying working with re:dom for some basics but hit a point where it wasn't clear what the recommended strategy was. Here's a simple example — the idea is that an app has a number of metadata sections, one of which is special and has some extra elements:

```javascript
export class MetadataDetails {
    constructor(sectionName, initialData) {
        this.el = html('details', {open: true}, [
            html('summary', [
                text(`${sectionName}:`),
                html('span.title', text(initialData.title))
            ]),
            html('div.details-body')
        ]);
    }
}

export class ItemMetadataDetails extends MetadataDetails {
}
```

The question would be what's the cleanest way for that subclass to add additional children? I could mount them in `onmount` or have the constructor call a method to process the list element list before adding it so the subclass would have the change to manipulate it but is there a reason to prefer one strategy over the other?

**Comment by pakastin** [comment]
Hi! Sorry it took me so long to answer. Here's one option:

```js
export class MetadataDetails {
    constructor(sectionName, initialData) {
        this.el = html('details', {open: true}, this.children = [
            html('summary',
                text(`${sectionName}:`),
                html('span.title', text(initialData.title))
            ),
            html('div.details-body')
        ]);
    }
}

export class ItemMetadataDetails extends MetadataDetails {
  constructor (sectionName, initialData) {
    super(sectionName, initialData);
    this.children.push( someNewChild );
    setChildren(this.el, this.children);
  }
}
```

**Comment by acdha** [comment]
Rest assured, I completely understand delays answering issues on open-source projects. Thanks for the suggestion — I switched from the `onmount`/`onunmount` method I'd been using since it's a little more explicit in its intention.

**Comment by pakastin** [comment]
Perfect! 👍
