### ISSUE TITLE
Error setting 'list' attribute for 'input' element

### ISSUE THREAD

**Issue by enquora** [redom/redom#142]
`redom.el('input', {type: 'text', value: some_value, list: 'some_list_id'})`
fails with error message
`TypeError: Attempted to assign to readonly property.`
when `setAttrInternal(...)` is called internally.

**Comment by pakastin** [comment]
Thanks, I’ll fix this ASAP! 👍

**Comment by pakastin** [comment]
Fixed and released as a patch, thank you for letting know! 👍👍
