### ISSUE TITLE
Attributes 'min' and 'max' for 'input' silently dropped

### ISSUE THREAD

**Issue by enquora** [redom/redom#143]
`redo.el('input', {'type': 'number', 'min': '1', 'max': '5', 'value': '3'});`
silently fails to process 'min' and 'max' attributes.

**Comment by pakastin** [comment]
Use number values, since RE:DOM automatically detects to use properties..

**Comment by enquora** [comment]
Behaviour is identical whether numeric or string values are used for 'min' and 'max' attributes - neither property is set on result element.

**Comment by aarongeorge** [comment]
@enquora is that because you're using `redo` instead of `redom`?

Doing this works just fine:
```
import { el, mount } from 'https://redom.js.org/redom.es.js';

mount(document.body, el('input', {'type': 'number', 'min': 1, 'max': 5, 'value': 3}));
```

**Comment by enquora** [comment]
This application is running in browsers predating support for the 'import' statement.

Creating an element using `redom.el('input', {'type': 'number', 'min': 1, 'max': 5, 'value': 3})` results in an element with no min or max attributes, verified by inspecting using the browser's DOM inspector.

This issue has not been resolved.

**Comment by pakastin** [comment]
Can you give me more specific information in which browser it doesn’t work?

**Comment by enquora** [comment]
It's true for the current versions of all browsers I've tried it in on my Mac - Safari, Firefox and Chrome.
I'll need to make a reduction for this, it seems. Note: I'm **not** using import, just including the redom library using a script tag and calling redom.el

**Comment by pakastin** [comment]
That’s really weird, since I also use those all the time. I’ll check in to it!

If you could create a jsfiddle for example which fails in your end, it would be easier to debug the issue..thanks! 👍

**Comment by enquora** [comment]
I've just made a reduction and it appears to be working. The problem is likely with usage in a custom component. I suspect now it's a coding error rather than a redom problem. 

You can close this again, or wait a day or so until I confirm this.

**Comment by pakastin** [comment]
Ok let’s do that. I am using both number and range input elements with min and max in many projects succesfully.. RE:DOM does very little magic there. Basically just detect if there’s a property (non-undefined), if not, it sets as attribute.
