### ISSUE TITLE
Need help to use framework

### ISSUE THREAD

**Issue by TheDozMan** [redom/redom#151]
I've read over the documentation on the redom website, also looked at the Project Generator code on github to try to work out where I'm going wrong but I need help...I'm sure its very simple....

I have a project structure as follows:

\public
\public\index.html
\public\src
\public\src\js
\public\src\js\app.js
\public\src\js\redom.es.min.js

The contents of index.html are as follows:
![index](https://user-images.githubusercontent.com/49174536/56883033-d0b3b900-6aa8-11e9-99ff-5dab79a17d83.PNG)

---------------------------------------------
And my app.js :
------------------------------------

import { el } from 'redom'; 

el('h1', 'hello from redom');

------------------------------------

But when I view the page, there is no "hello from redom". 

I'm sure that I am doing some thing really dumb....can you help me out?

thanks!

**Comment by data-handler** [comment]
Hi
You need to mount the element to the dom using the redom mount function

**Comment by TheDozMan** [comment]
Tried the below, but still nothing:


import { el, mount } from 'redom'; 

const heading = el('h1', 'hello from redom');

mount(document.body, heading);

**Comment by TheDozMan** [comment]
I also changed by script tag to include type="module" - Which I think got me a bit further but I think it's a CORS issue now.

**Comment by pakastin** [comment]
You need to have http/https protocol if using module import, file:// can’t do..

**Comment by pakastin** [comment]
Also if you’re not using bundler, please try:
```js
import { el, mount } from 'https://redom.js.org/redom.es.min.js';
```
https://redom.js.org/documentation/#es2015

**Comment by TheDozMan** [comment]
Ah yes...I need to set up a local https server. Thanks for the help!

**Comment by TheDozMan** [comment]
Awesome! ... All working now. I used node/npm to set up a local https server :-)

changed my import to './redom.es.min.js'     (just so I don't have to connect to internet).

Thanks @data-handler  & @pakastin

**Comment by pakastin** [comment]
Perfect, glad you got it working! 👍
