### ISSUE TITLE
About List Item Wrapper

### ISSUE THREAD

**Issue by Leeingnyo** [redom/redom#153]
Hi! I'm very excited with finding RE:DOM, and I move my project to RE:DOM from Angular.
Thank you for this small but perfect library.
and I have a question about usage RE:DOM

here is the dom tree what I want to build.

```html
<ul class="list">
  <li class="item">
    <component />
  </li>
  <li class="item">
    <component />
  </li>
</ul>
```

to do this with redom, I wrote this code first.

```js
import { el, mount, list } from 'redom';
import Component from './component';

class ComponentWrapper {
  constructor(Item) {
    this.el = el('li.item', this.item = new Item());
  }
  update(data) {
    this.item.update(data);
  }
}

var list = list('ul.list', ComponentWrapper.bind(ComponentWrapper, Component));
mount(document.body, list);
```

It works well.
after some times, i fixed code like this to use with other components

```js
import { el } from 'redom';

export class Wrapper {
  constructor(wrapper, View, ...args) {
    this.el = el(wrapper, this.view = new View(...args));
  }

  update(...args) {
    this.view.update(...args);
  }
}

export function wrap(wrapper, View, ...args) {
  return Wrapper.bind(Wrapper, wrapper, View, ...args);
}
```

```js
import { mount, list } from 'redom';
import { wrap } from 'redom-utils'; // :)
import Component from './component';

var list = list('ul.list', wrap('li.item', Component));
mount(document.body, list);
```

what about embedding this feature into redom, or is there elegant way to do this? because `list()` requires View as a constructor only, we should make another constructor to expand that. I think that It'll be helpful to expand component easily.
by the way, I misunderstood `list.extend()` to do this thing first..

Hmm... but I don't want redom to be verbose, either.
Thanks again this great package!

**Comment by pakastin** [comment]
Have you tried `el.extend`? It makes element factory, which works with `list` too 😉

**Comment by Leeingnyo** [comment]
Ah I'll try it! Thank you

**Comment by Leeingnyo** [comment]
Umm.. i'm sorry that I couldn't understand what to do with `el.extend`

`el.extend` returns bound `html` which is not not a constructor, but `list` requires constructor as a second parameter (`listpool` use `View` with `new` keyword).

here is my test code

```html
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/redom/3.20.1/redom.js"></script>
<script>
const { mount, el, list } = redom;

class Component {
  constructor() { this.el = el('span'); }
  update(data) { this.el.textContent = data; }
}

/* what i want
<ul class="list2">
  <li class="item"><span>foo</span></li>
  <li class="item"><span>bar</span></li>
  <li class="item"><span>baz</span></li>
</ul>
*/
</script>
<script>
var li = el.extend('li.item', new Component());
var ul = list('ul.list', li);

ul.update(['foo', 'bar', 'baz']); // error

mount(document.body, ul);
</script>
</body>
```

Could you show me an example? sorry to bother you

**Comment by pakastin** [comment]
hmm..yeah you’d need an update method there

I’ll get back to you when I’m on my laptop (on mobile now)

**Comment by pakastin** [comment]
Maybe that could be a separate add-on? I would even like to separate redom-list to it's own add-on as well (also router, place, etc..) at some point..

**Comment by Leeingnyo** [comment]
Ok! thank you for discussing together.

**Comment by pakastin** [comment]
No worries, anytime! 👌
