### ISSUE TITLE
Question: sideEffects flag in package.json

### ISSUE THREAD

**Issue by oafx** [redom/redom#155]
Hi,

this is more of a question as I'm pretty new to the whole tree-shaking and side-effects topic but i've noticed that it's not possible to just import a single module i.e. { el } from redom without having the whole redom package in the bundle.

While this may totally make sense I still figured I'd ask if it would be possible to set this flag in your package and if not then why. Maybe your answer will help me understand the whole topic a bit better :)

Thanks
Chris

P.S.: great work with this package!

**Comment by pakastin** [comment]
Thank you! 😎👍
It should tree shake alright.. Which bundler you’re using and how?

**Comment by pakastin** [comment]
Could you educate me how that flag works?

**Comment by pakastin** [comment]
Added and published, thank you for letting me know about the flag!
