### ISSUE TITLE
Make Router and Place to Support Plain Node and Instance of Component

### ISSUE THREAD

**Issue by Leeingnyo** [redom/redom#156]
Hi,

## make `Router` to support plain node

With using RE:DOM, I made helper function `functionify` like this.

```js
class FunctionWrapper {
  constructor(el) {
    if (el.el) { // to support component instance
      this.view = el;
      this.el = el.el;
    } else { // plain node
      this.view = null;
      this.el = el;
    }
  }

  update(...args) {
    this.view && this.view.update && this.view.update(...args);
  }
}

export function functionify(el) {
  return FunctionWrapper.bind(FunctionWrapper, el);
}
```

and I realized that I used my `functionify` usually `router`, specially for plain nodes.
Since `place` can take plain node, I think that `router` could do, too.
and it's necessary for the consistency;
It's helpful with the following situation.

```js
class NoticeList {
  constructor() {
    this.listBottom = router('.notice__list-bottom', {
      moreButton: (this.moreButton = el('button.more-button', 'show more')),
      noMoreText: el('span', 'there is no more information')
    });
    this.list = list('ul.notice__list', Notice);
    this.el = el('section.notice', this.list, this.listBottom);
    this.moreButton.onclick = event => console.log('show more');
  }
}
```

## make `Router` and `Place` to support the instance of Component

I used the `functionify` with `place`, like `place(functionify(componentInstance))`. I think that we could expand the `Place`, the `Router` to support the instance of component which has property `el`.
I read https://github.com/redom/redom/issues/105. If we treat a function as only a Constructor and throw away the case of `ListPool`, it could be more simple.

## ETC

I tried to test my idea and make PR for this, but I couldn't run the test... Don't the test generate any stdout?

```sh
./node_modules/browserify/bin/cmd.js -t coverify test/index.js | ./node_modules/tape-run/bin/run.js | ./node_modules/coverify/bin/cmd.js
```

this generates nothing, though I modify the test case to fail (`t.ok(setAttr == null);`);
only what I did is `npm install` after cloning.

and I can't use `watch.js` because my editor, vim, generates `.swp` files in the `esm` directory... never mind this :)

**Comment by pakastin** [comment]
Good points! Adding now..

**Comment by pakastin** [comment]
Added support for all those and published in [v3.22.0](https://github.com/redom/redom/releases/tag/v3.22.0)! 😉

**Comment by Leeingnyo** [comment]
Thank you for the very quick reaction!

**Comment by pakastin** [comment]
No worries!
