### ISSUE TITLE
component mounted several times (list, update)

### ISSUE THREAD

**Issue by Leeingnyo** [redom/redom#158]
Hi, I'm making some simple template system with RE:DOM to support to render dynamic contents. and I have a problem with `list`.

when I updated the instance of `List`, the children was mounted though its parent was not mounted.
after that time, when parent mounted, the children was mounted again! (it triggered `onmount`, not `onremount`)

Here is [the example](https://github.com/Leeingnyo/redom-example) to reproduce my problem.

I struggled with this for days...

Questions:
Is this a bug on `list`?
If not, what should I do to achieve my goal?

Thanks you.

**Comment by pakastin** [comment]
Seems like a bug yeah, shouldn’t do that. I’ll check it out!

Rarely use lifecycle events myself..

**Comment by Leeingnyo** [comment]
Actually, the real problem is that unmount event (which of `Inner` instance in the example) isn't fired in my real page. but I can't reproduce it with the example... I try to figure out the reason.

I usually use lifecycle events to bind listeners on the global store or on an emitter (such as window resize event emitter). this issue causes memory leak...

**Comment by pakastin** [comment]
I tend to avoid using state listeners, but yeah I'll investigate this.

**Comment by Leeingnyo** [comment]
> Actually, the real problem is that unmount event isn't fired

I found the reason. reproduced [here](https://github.com/Leeingnyo/redom-example/tree/another-issue). If parent component has no event handler, the children's one isn't fired (I'm not sure that this situation is happened if child is only a `list`)

So, I solved my problem (memory leak) by calling unbind function in `onmount` temporarily.

I hope that these examples help you to find a solution.

Thank you!

**Comment by pakastin** [comment]
It probably has something to do with [this line](https://github.com/redom/redom/blob/96bccd68829f3ab2d5e7b9af9dbb55466f324a44/esm/mount.js#L98). I'll run some further tests..

**Comment by pakastin** [comment]
Have you tried without your custom wrapper?

**Comment by pakastin** [comment]
https://github.com/Leeingnyo/redom-example/blob/fb7696448de491e2e0e1799309a9c515351a07bf/index.html#L10

This line should probably be `this.el = el(wrapper, this.__redom_view = new View(...args));`, however your way of wrapping is not recommended..

**Comment by pakastin** [comment]
I believe [this line](https://github.com/redom/redom/blob/e120a1a286625904ef29415db983a543b15fecd4/esm/mount.js#L98) was the root cause. Think it's fixed now.

**Comment by Leeingnyo** [comment]
Yeah! It works! I checked that this is fixed at the example.
Thank you very much!

**Comment by pakastin** [comment]
No worries, thanks for reporting! 👌
