### ISSUE TITLE
TypeError: parent is undefined

### ISSUE THREAD

**Issue by truecastdesign** [redom/redom#165]
I'm having an issue I can't solve with the update prototype method.

var filters = [
	{title:'Volts', options:'ff'},
	{title:'Type', options:'ff'}
];

I created a class

class FilterButton {
		constructor() {
			this.button2 = el('button', 'hello');
		}
		update(data) { console.log(data);
			this.button2.textContent = data.title;
		}
	}

Then: 

var filterButtons = list('div', FilterButton);
filterButtons.update(filters); // line 653

I have tried all kinds of things and I keep getting a TypeError: parent is undefined error.

Here is the error trace:

getEl http://www.batterystuff.test/assets/js/redem.js:383
update http://www.batterystuff.test/assets/js/redem.js:537
update http://www.batterystuff.test/assets/js/redem.js:576
<anonymous> http://www.batterystuff.test/battery-chargers/volt/83/:653

Can you see what I'm doing wrong? Thanks

**Comment by mrwanashraf** [comment]
the links that you shared aren't working therefore i can't view the error trace.

can you provide us with a working link so that we help you with your issue?

**Comment by truecastdesign** [comment]
The site is not in production.

The line numbers for the non compressed redem script are listed and the function they are calling.

It is the getEl function called from update.

Any ideas?

**Comment by Leeingnyo** [comment]
I think your `FiterButton` class should have `el` property.

```
class FilterButton {
  constructor() {
    this.el = this.button2 = el('button', 'hello');
  }
  update(data) {
    console.log(data);
    this.button2.textContent = data.title;
  }
}
```

redom components should have `el` property
