### ISSUE TITLE
Instanced class is valid list item argument type but will result in a runtime error

### ISSUE THREAD

**Issue by katywings** [redom/redom#170]
The current RedomComponentConstructor type includes already instanced redom components as viable constructors. Using instanced redom components in list and similar methods however results in a runtime error `View is not a constructor`.

Demo: https://codesandbox.io/s/cranky-nash-90y4f
Notes: as you can see typescript will not warn that the instanced List item actually is wrong. 
Change that resulted in this problem: #166

Recommendation: remove RedomComponentClass again from RedomComponentConstructor at https://github.com/redom/redom/blob/master/index.d.ts#L34

Anyone knowing why RedomComponentClass actually was added to RedomComponentConstructor? @fishead / @raulil

**Comment by fishead** [comment]
Yes, the PR #166 I created is nonsense.

According to the code 
https://github.com/redom/redom/blob/c4210f5450df6b9a998b3634ff5a3fabbec3bfc8/esm/listpool.js#L37  
The 2nd argument (a.k.a `View`) will be called with `new` keyword, and only `class` or `constructor function` can be called with `new` for now.

Let's revert the type definition first.

```typescript
export interface RedomComponentConstructor {
    new(): RedomComponent;
}
```

Then consider the code below.

```typescript
import { el, list } from "redom";

class ListItemClass {
  el = el("li");

  update(label: string) {
    this.el.textContent = label;
  }
}

// good
const aList = list("ul", ListItemClass);

// bad, instance can not use with `new` keyword
const bList = list("ul", new ListItemClass());

function ListItemFunction() {
  this.el = el('li')

  this.update = function (label: string) {
    this.el.textContent = label;
  }
}

// should be good, normal function can use with `new` keyword,
// but TypeScript report error
const cList = list("ul", ListItemFunction);

// should be bad, instance can not use with `new` keyword
// but TypeScript does not report error
// because type of `new ListItemFunction()` is `any`
// read https://github.com/microsoft/TypeScript/issues/27328
const dList = list("ul", new ListItemFunction());
```

Maybe the type definition should be changed to.
```typescript
// read https://stackoverflow.com/questions/52349758/how-does-type-constructort-function-prototype-t-apply-to-abstract-c
export type RedomComponentFunction = Function & { prototype: RedomComponent }

export interface RedomComponentClass {
    new(): RedomComponent;
}

export type RedomComponentConstructor = RedomComponentClass | RedomComponentFunction;
```

English is not my mother tongue, hope I represent myself clearly.

**Comment by katywings** [comment]
Thanks for your comprehensive details :)

I am not sure if @raulil would like that `Function` thing xD, he and I had many discussions regarding accepting function constructors in list, so I also removed a much more simplistic function constructor solution from my own pr in:
https://github.com/redom/redom/commit/8783c0f10c521c3729152f665a9e900f320ce568
```typescript
// should be good, normal function can use with `new` keyword,
// but TypeScript report error
const cList = list("ul", ListItemFunction);
```
Did you try this out with the `& { prototype: RedomComponent }`? That would be huge!

**Comment by fishead** [comment]
I tried it on my Mac，the code comes from here https://stackoverflow.com/questions/52349758/how-does-type-constructort-function-prototype-t-apply-to-abstract-class

**Comment by katywings** [comment]
I prepared the work for the RedomComponentClass rename and the fix of RedomComponentConstructor in this branch: https://github.com/lufrai/redom/tree/task/%23170-redomComponent-types

- RedomComponentConstructor fix: https://github.com/lufrai/redom/commit/ad67b4c9bf5de3be26a88f5cbe294b1cfcf096a6
- Rename: https://github.com/lufrai/redom/commit/bac9e3af3f6ef924d37625a62b42f5b9e2929240

**Comment by fishead** [comment]
Sorry for the delay, it's festival in China.

I am OK with your recommendation. All there troubles are made by my lack of understanding TypeScript. Deeply sorry for this.

**Comment by katywings** [comment]
@fishead Nuu worries :D, hope you enjoyed the festival ;)
