### ISSUE TITLE
Attributes leaking to el item of component

### ISSUE THREAD

**Issue by sc0ty** [redom/redom#192]
I'm not sure if this is a bug or expected behaviour, but when I'm creating component with some custom attributes like this:
```javascript
const { el, mount } = redom;

class Test {
  constructor(attrs) {
    this.el = el('p', {style: {color: attrs.color}}, 'hello world');
  }
}

const hello = el(Test, {color: 'red'});
mount(document.body, hello);
```

Attributes are also added to `this.el`. Here `color="red"` is added to `<p>`:
```html
<p color="red" style="color: red;">hello world</p>
```

I could observe similar situation with children - they are added to `this.el`. Since they are passed to constructor I was expecting that I should manually put them where I wan't them in my component.

**Comment by mrwanashraf** [comment]
I highly suspect that this is a bug as this is attribute is not a valid attribute in any html tag.

I marked this Issue as bug until the opposite is proved.

**Comment by sc0ty** [comment]
It's not just `color` attribute, but every attribute is added like that. But I'm not sure if my use case is valid, I couldn't find answer in docs.

**Comment by pakastin** [comment]
It’s a feature of the flexibility of arguments. 
Probably not the most commonly used that way though.

**Comment by pakastin** [comment]
If you want to provide arguments to component, just use `new Test({ a, b })`
