### ISSUE TITLE
Possibly incorrect/incomplete type definition for lists

### ISSUE THREAD

**Issue by flery** [redom/redom#199]
I created an issue (#173) some time ago regarding list constructor function, which was solved by an existing feature. Thing is I am using typescript and I think the type def is not up to date for that feature. Should the list creation type def not use 'RedomComponentCreator' instead of 'RedomComponentConstructor'?

**Comment by RauliL** [comment]
Hi,

It seems that you are correct, and the constructor should use `RedomComponentCreator`. Contributions are always welcome.

**Comment by joona** [comment]
yes, sounds about right to me as well. I'll push a PR.

**Comment by flery** [comment]
Thanks, would have done it myself. But was unsure about it and am not yet versed in the github procedures.

**Comment by pakastin** [comment]
Released now, thank you! 💪

**Comment by pakastin** [comment]
https://github.com/redom/redom/releases/tag/v3.26.0
