### ISSUE TITLE
URL Router

### ISSUE THREAD

**Issue by TareqK** [redom/redom#202]
Hello,
So i was toying around with routing, and i got a very rudimentary URL router working. It took around 10 lines of code, and with maybe another 20-30 lines of code i think we can add a URL router with middleware callbacks. How do you feel about that 

```js
window.onhashchange = (e) => { 
     doRoute()
}

window.onload = (e)=>{
    doRoute()
}

const doRoute= ()=> {
     let routeUrl = window.location.hash.substr(1).split('/');
     let view = routeUrl[0];
     let params =  routeUrl.splice(1,routeUrl.length)
     app.update(view,params)
}
```

I want to add it in, but im not sure where to put it. Some pointers would be super nice. I know that we want to keep RE:DOM small and tiny, but i think a feature like this would be super nice.

**Comment by pakastin** [comment]
That’s similar what I do, but in some projects I use hash, while in some projects I use pushstate. Sometimes I even use search query, like in aviamaps.com for example.

I’d like core to be flexible and would encourage to write a small library instead. If it’s good, I can include it in github.com/redom org 😉

**Comment by TareqK** [comment]
> That’s very similar to what I do, but in some projects I use hash, while in some projects I use pushstate. Sometimes I even use search query, like in [aviamaps.com](https://aviamaps.com) for example.
> 
> I’d like core to be flexible and would encourage to write a small library instead. If it’s good, I can include it in [@redom](https://github.com/redom) org wink

Great ! Ill get started on the project, and ill ping you here once something is done and we can transfer it

**Comment by TareqK** [comment]
@pakastin  Ive finished the basic routing, it has params, and basic middleware functionality with a default route when views are not found/no view is specified.
