### ISSUE TITLE
RE:DOM SPA framework inclusion into the redom organization

### ISSUE THREAD

**Issue by TareqK** [redom/redom#204]
hi @pakastin , like we talked about a couple of days ago in #202 , I created the simple routing/SPA framework we were talking about. here is the link of the repository

https://github.com/TareqK/redom-app

Look into it, and tell me if we need anything else, and if its possible to include it under @redom

**Comment by TareqK** [comment]
@pakastin  Any Updates?

**Comment by TareqK** [comment]
@pakastin  Have you had a chance to look at this?

**Comment by pakastin** [comment]
It’s pretty specific and opinionated, so I’m not currently seeing it as generic library for anyone to use 🤔

**Comment by TareqK** [comment]
@pakastin  Do you mind giving a but more details on what you mean ? I mean the point was just to cover hash routing and middleware
