### ISSUE TITLE
reusing created element with el in multiple locations

### ISSUE THREAD

**Issue by samadadi** [redom/redom#220]
I am writing a simple counter app which has two increment and decrement buttons. In this app, I am using counter element in multiple location as test but I just see the first one that I added in this.el. Is this a bug or I am missing something?

    this.counter = el("p.counter", counter);

    this.increment = el("button.increment", "Increment");

    this.decrement = el("button.decremtn", "Decrement");

    this.another = el("p.another", this.counter);

    this.el =
            el("div.counter",
                this.counter,
                this.another,
                this.increment,
                this.decrement);

**Comment by Leeingnyo** [comment]
`el()` makes a dom element instance.
The same dom instance can't be attachable at difference positions in dom tree. it'll be moved!

> If the given child is a reference to an existing node in the document, appendChild() moves it from its current position to the new position (there is no requirement to remove the node from its parent node before appending it to some other node)
> 
> *in MDN [`Node.appendChild()`](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild)*

Check other method `Node.insertBefore()` too.

you should make another dom instance or copy it with [`Node.cloneNode()`](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode)
Note: the cloned dom instance dosen't have event listeners.

**Comment by pakastin** [comment]
There’s also Node.cloneNode(true), which also clones children 😎

But yeah, RE:DOM just creates regular HTML elements, so user should know the basics of the DOM.
