### ISSUE TITLE
Explicit Table Creation Example

### ISSUE THREAD

**Issue by ExtendedInterlude** [redom/redom#244]
I am trying to make a table in a more explicit manner with regular components and `list`, not through the `list('table', Tr)` route. This was so I could pass around the type `Table` instead of an instance. Please find below what I currently have.

```typescript
class Column {
    el: HTMLElement;

    private image: HTMLElement;
    
    constructor() {
        this.image = el('img', { src: 'someimage.jpg' });
        this.el = el('div', { class: 'col-md-3' }, this.image);
    }

    update(image: Image) {
      this.image.src = image.src;
    }
}

class Row {
    el: List;

    constructor() {
        this.el = list(el('div', { class: 'row' }), Column);
    }

    update(images: Image[]) {
        this.el.update(images);
    }
}

class Table {
    el: List;

    constructor() {
        this.el = list(el('div', { class: 'container' }), Row);
    }
    
    update(images: Image[][]) {
        this.el.update(images);
    }
}
```

The error lies in the `Row` of `this.el = list(el('div', { class: 'container' }), Row);`.

```
Argument of type 'typeof Row' is not assignable to parameter of type 'RedomComponentClass'.
  Construct signature return types 'Row' and 'RedomComponent' are incompatible.
    The types of 'el' are incompatible between these types.
      Type 'List' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 233 more.ts(2345)
```

This error also occurs when I do the less explicit method detailed in the documentation and with the exact code of the `Regular component` section with added types.
```typescript
export const Table = list('div.container', Row);
```

How would I properly achieve this table setup?

**Comment by pakastin** [comment]
Seems like some kind of TypeScript error, could @katywings take a look for example (I’m not familiar with TypeScript). Should work with JavaScript alright.

**Comment by katywings** [comment]
Hey :)
I don't have time to code around in Redom at the moment but I can give you a hint:

Currently a RedomComponent is only a redom component, if its el is a Html or SvgElement https://github.com/redom/redom/blob/master/index.d.ts#L16

@ExtendedInterlude s Row component however insteas has another redom component as el. 

You would have to try it out but I think you can just change the line from my linked file to:
```
el: HTMLElement | SVGElement | RedomComponent;
```

**Comment by mrwanashraf** [comment]
@katywings I will do it

**Comment by ExtendedInterlude** [comment]
Thanks @katywings and @mrwanashraf, edited locally and this fixed the issue for me. Not sure of the etiquette but can this be closed now or after the fix is in a release?

**Comment by mrwanashraf** [comment]
its already merged, so its coming up in the next release, I will go ahead and close this Issue now as you have reported that the issue got fixed on your side.

**Comment by pakastin** [comment]
Published as patch!
