### ISSUE TITLE
Idea: Auto map update

### ISSUE THREAD

**Issue by jon49** [redom/redom#257]
Just an idea but it would be cool to be able to auto map the update method. E.g.,

```js
const h1 = el('h1', { update: {
  title: 'myVariableName',
  text: 'variableName2',
  'data-id': 'id' 
}})

h1.update({
  myVariableName: 'This is the title on hover',
  variableName2: 'The title of the H2',
  thisVarDoesNotExist: 'will do nothing'})
  // id not sent so it isn't updated
```

This would remove much of the boiler plate and keep the mapping closer to the creation of the elements. I was using Stage0 and that was the most annoying part of it. Not having a simpler mapping directly in the template. I'm actually moving most of my dom creation over to the service worker. But for web components it would be nice to have a small lib like RE:DOM. As the creation of the JS is pretty messy otherwise.

I did something similar in this mapping mechanism when serving my pages from a service worker so it implemented a bit differently:

https://github.com/jon49/MealPlanner/blob/99c271f7e92350684d040c0bdd550f92eb8d4dcb/play/index.html#L18

Another advantage is that the user of the library will not need to worry about gotchas like checking the `src` attribute.

**Comment by pakastin** [comment]
Wow, really nice idea! 👌

**Comment by jon49** [comment]
Another idea about this would be to add in a function modifier that could do this for you - like an add on/extension. That way the library can stay small and then only if you really want this feature you can add it in with the extension. I might be making this more complicated than needed though :-). I don't know how much bigger this would make the library.

**Comment by NetLancer** [comment]
I love redom although haven't dealt with it in practice but kinda keep close attention to its progress & popularity. I personally think it deserves more devs/users attention given its characteristics: tiny, simple, close to standards, no virt.dom and maybe some more..:).  
Well, being such i tend to think of it as a good& proper tool for enterprise type of things, which is my first concern.
I think especially these days when we have all the general purpose giants in the industry, giving the library its niche would help make decisions about new features and adding to the library overall weight.. 
Huge thanks to developers/maintainers of such a usefull tool, i really hope it'll grow in stability, adoption and useful features fast enough :))

**Comment by pakastin** [comment]
RE:DOM is actually created for enterprise purposes. We use it in iDiD digital signage (https://idid2.fi) to run both the manager and players. That makes our system to run even in low end devices with minimum memory consumption and precise render management.

In all other projects I use RE:DOM as well, like in Aviamaps (https://aviamaps.com) and https://Avain.app

I have planned to make videos about state and render handling in bigger apps, when I just have time..

**Comment by jon49** [comment]
I had forgotten about this. I couldn't figure out how to do this like the Re:Dom API. But I was playing with different ideas. Here's one that uses nested arrays (733 B minified - but needs some optimizations added):

https://github.com/jon49/RootDom

And here is one that takes Stage0 and adds an updater (1.87 kB minified - can be made smaller if you put the template in the HTML file and remove that code from the lib):

https://github.com/jon49/MealPlanner/blob/master/src/app/utils/hash-template.js

**Comment by jon49** [comment]
Here's a combo of lfn a small lib similar to redom with my updater.

https://github.com/jon49/WeightTracker/blob/d4ad3d474a1c6e0bac090f27d10cf447a675a816/WeightTracker/src/static/web/js/h.js

https://github.com/ryanford/lfn
