### ISSUE TITLE
Problem to render a component

### ISSUE THREAD

**Issue by EvandroLG** [redom/redom#317]
I created a page component with the following code:

```js
import { el } from "redom";

class Home {
  public el;

  constructor() {
    this.el = el("h1");
  }

  update() {
    this.el.textContent = "Home";
  }
}

export default Home;
```

And I've this main js file:
```js
import { el, mount, router } from "redom";
import Home from "./pages/Home";

const app = router("div#app", {
  home: Home,
});

mount(document.body, app);
```

The `h1` element is being added in the DOM tree, but without any text inside it.
Am I missing something here?

**Comment by pakastin** [comment]
Seems alright 🤔 Did you try app.update('home', data);

**Comment by EvandroLG** [comment]
If I call the `update` method, it works fine @pakastin 
Checking the implementation of the `mount` method, I see we never execute the update function there. 
For your information, `update` is finishing the execution here: https://github.com/redom/redom/blob/master/esm/mount.js#L100

If we execute mount passing a `Router`, we should always execute the update method if it exists, am I right?

Another thing, what should happen if I've something like it within my constructor: `this.el = el("h1", "Home")`?

**Comment by pakastin** [comment]
Default route for router is `null`, so unless you define it by calling `router.update(route, data)`, it shouldn't even show home.

**Comment by EvandroLG** [comment]
Okay. In this case, it's working as expected, right?
Anyway, is it possible to add a content inside `el` without calling the `router.update` method?

**Comment by pakastin** [comment]
Route can be just regular `element` and not class, so you could create default route:
```
router({
  default: el('h1', 'Home')
});

app.update('default');
```

**Comment by pakastin** [comment]
You could also actually try:

```
router(el('h1', 'Home'), {
  home: Home
});
```

**Comment by pakastin** [comment]
Router replaces parent element's content with current route, so unless you call update, it should use text element `'Home'` as default content.

**Comment by pakastin** [comment]
Here's router's source, it's logic is really simple:
https://github.com/redom/redom/blob/master/esm/router.js

**Comment by EvandroLG** [comment]
@pakastin I'd expect that once I've this line `this.el = el("h1", "Home")` in my constructor, I'd generate `<h1>Home</h1>`. Does it make sense to you?

**Comment by pakastin** [comment]
I mean router shows just the wrapper as default, you need to call it's `update` to set route.

**Comment by pakastin** [comment]
Otherwise you could add default content to wrapper, which gets replaced by route once you call `update`

**Comment by pakastin** [comment]
btw. you can message me in Messenger, probably easier to continue there 😛

https://m.me/pakastin

**Comment by EvandroLG** [comment]
Sure, I'll close this. Tks @pakastin
