### ISSUE TITLE
mount with replace option

### ISSUE THREAD

**Issue by data-handler** [redom/redom#339]
When using mount with replace, why isn't the replaced component's 'onunmount' lifecycle function called?

[codepen](https://codepen.io/kindasonic/pen/PobbvQG)

**Comment by pakastin** [comment]
Sorry I haven't noticed this, I'll check it out!

**Comment by data-handler** [comment]
Hi. Any update on this issue? Thanks

**Comment by neerajkanhere** [comment]
I'm fairly new to frontend development and really like RE:DOM for its simplicity and minimal-magic approach. 

I took a stab at this issue and not sure if it's really as simple as this:

```
diff --git a/esm/mount.js b/esm/mount.js
index b8c13e6..ec7ddb1 100644
--- a/esm/mount.js
+++ b/esm/mount.js
@@ -28,6 +28,9 @@ export function mount (parent, child, before, replace) {
 
   if (before != null) {
     if (replace) {
+      if (before.el && before.el.__redom_mounted) {
+        trigger(before.el, 'onunmount');
+      }
       parentEl.replaceChild(childEl, getEl(before));
     } else {
       parentEl.insertBefore(childEl, getEl(before));

```
The example @data-handler linked to seems to work with the change above but I'm not sure if this has unintended consequences.

**Comment by aarongeorge** [comment]
@pakastin I think this should be looked at now. It's a legitimate use-case and currently is causing problems.

Not sure I'd implement the fix the way @neerajkanhere has (as doUnmount should be used instead). If you'd like someone else to implement the fix and add a test I can do that, I just want to know this will be merged into main and not have to maintain a separate branch.

Keen to hear your thought :)

**Comment by pakastin** [comment]
Released in v3.28.0, thanks for contribution!

**Comment by aarongeorge** [comment]
Thanks @pakastin , any reason to call `trigger` instead of something similar to what currently exists?

```javascript
if (before != null) {
	if (replace) {
		var beforeEl = getEl(before);
		if (before === beforeEl && beforeEl.__redom_view) before = beforeEl.__redom_view;
		if (before !== beforeEl) beforeEl.__redom_view = before;
		if (beforeEl.parentNode === parentEl) doUnmount(before, beforeEl, beforeEl.parentNode);
		parentEl.replaceChild(childEl, getEl(before));
	} else {
		parentEl.insertBefore(childEl, getEl(before));
	}
} else {
	parentEl.appendChild(childEl);
}
```

**Comment by pakastin** [comment]
Well, because `doUnmount` unmounts the element, so there's no element to replace with after that 😅
