### ISSUE TITLE
create a list without specify parent element

### ISSUE THREAD

**Issue by smallswan399** [redom/redom#343]
Hello guys!

I want to create a pagination bellow using redom list

```
  <ul>
    <li class="goto-first">first</li>
    <li class="item">1</li>
    <li class="item">2</li>
    <li class="item">3</li>
    <li class="goto-last">last</li>
  </ul>
```

The `ul`, the first and last `li` are static html
There are only 3 `li` elements (between the first and the last `li`) that I want to handled by redomjs

The problem is that redom list always ask a parent element to construct the list like `list('div', Li)`
The generated html will be like

```
<ul>
    <li class="goto-first">first</li>
      <div>
        <li class="item">1</li>
        <li class="item">2</li>
        <li class="item">3</li>
      </div>
    <li class="goto-last">last</li>
  </ul>
```

That is what we don't want

Of course we have walkarounds, but I wonder is Redomjs able to handle this issue out of the box?

**Comment by Leeingnyo** [comment]
please try this answer! https://github.com/redom/redom/issues/173#issuecomment-579222237
It might be helpful
