### ISSUE TITLE
ESM builds are ES5, not ES6

### ISSUE THREAD

**Issue by pjeby** [redom/redom#438]
It appears that the ESM builds (dist/redom.es.js and dist/redom.es.min.js) are ES5 code, which introduces some issues when trying to use a tree-shaking bundler, as they can't properly detect when certain classes are being used in that case.  (Specifically, using esbuild to build a redom project will always end up including Router and svg, even if they're not used.)

This can be worked around (sort of) by importing from "redom/esm" instead of "redom", but then typescript throws up errors because there aren't any types declared for redom/esm.  So it would be helpful if redom either didn't downlevel the es builds (since es modules themselves are a >ES2015 feature), or alternately just set the `module` in package.json to `redom/esm/index.js` so bundlers will just use the original source to compile from, allowing the user to determine what runtime environment they're targeting.

**Comment by pakastin** [comment]
Indeed, needs refresh 👍

**Comment by pakastin** [comment]
https://github.com/redom/redom/releases/tag/v4.0.0
