### ISSUE TITLE
mount into a dom element by selector

### ISSUE THREAD

**Issue by prakashraman** [redom/redom#442]
Hey,

Looks like a great library. I was unable to find (or infer) a way we can `mount` the created element into, say, a different element other than `document.body`

Would something like this work?

```
const element = el("h1", "hello world");
mount("#root", element)
```

Thanks!

**Comment by pakastin** [comment]
Try:

```
mount(document.querySelector('#root'), element);
```

**Comment by prakashraman** [comment]
Yeah, something similar worked.

Since I am developing in Typescript, I was getting the type-error. The following are working

```
mount(document.querySelector("#root")!, el("h1", "hello world")); // note the "!"
mount(document.getElementsByTagName()[0], ....)
```

Thanks!

**Comment by pakastin** [comment]
I'm not familiar with Typescript, but glad you get it to work! 👍
