### ISSUE TITLE
Version 3.29.0 Introduces breaking changes

### ISSUE THREAD

**Issue by TroyMcl** [redom/redom#446]
Commit 01fe960730e923378805d70a125098acff8d0310 "Don't use DOM memoization" introduced a breaking change to the html function. It will break existing code using memoization and the change is not reflected in TypeScript types thus bypassing any warning that your code has a problem.

Removing the isNode() check from html function will cause any code using memorization to break. This change means passing in a node or redom component as the first argument, which was previously supported, now fails all the checks and throws an error. This change of acceptable first parameter inputs is not reflected in the TypeScript types for v3.29.0. The TS compiler still shows RedomElQuery of type 'Node | RedomComponentCreator' as being acceptable inputs, meaning the code compiles without any warning that there is now a breaking change in the code.

My main reason for opening this issue ticket is around versioning. I would propose that this kind of breaking change should require a major version change, not a minor version change. Major version 3 should be reverted to keep memorization in the html function, and a new major version should be implemented with memorization removed, and updated types.

**Comment by pakastin** [comment]
Good point! 👍
