### ISSUE TITLE
List update after sorting data

### ISSUE THREAD

**Issue by data-handler** [redom/redom#452]
I'm not sure if this is an issue or me not using redom correctly.

I have a Table component with a list of TableRow components:

```
class Table {
    constructor() {
        this.el = el('table',
            el('thead',...),
            this.body = el('tbody')
        );
        this.rows = list(this.body, TableRow);
    }
}
```
Each row has a unique id.
When a row is selected (by clicking) I add a css class to it.
If I sort the data then call rows.update(data) a different row becomes selected.
It appears the list 'remembers' the index of the selected row, not it's id.

Is there a way to make the list retain the selected row by id, other than manually doing it (which is what I am doing as a workaround)?

**Comment by pakastin** [comment]
define id with the list's third parameter: https://redom.js.org/#lists

If your id key is called `id` for example, then use:

```js
this.rows = list(this.body, TableRow, 'id')
```

**Comment by data-handler** [comment]
Thank you very much! 👍
