### ISSUE TITLE
Is there any standard project template available for redom?

### ISSUE THREAD

**Issue by tamilvendhank-helptap** [redom/redom#461]
Hello,

Is there any standard project template available for redom, like `create-react-app`, which has the setup for all sorts of things to start writing the code?

**Comment by pakastin** [comment]
There's no need to setup anything. You can even start like:

```html
<script src="https://redom.js.org/redom.min.js"></script>

<script>
const { el, mount } = redom;

mount(document.body, el('h1', 'Hello world!'));
</script>
```

**Comment by tamilvendhank-helptap** [comment]
Yeah, I know. I was going to setup an interview task, in which the interviewee needs to build a full stack application. I wanted them to use redom, because we are already using it. But, thought, without `create-react-app` kind of project `scaffolders`, it might take too long for them to complete the interview task. I was simply wondering if there is anything like that for Redom. I guess it does not present, yet.

But, I agree with you that, one do not need such thing to get started with Redom. Last week I did initialized a project with Redom, SCSS & HTML as fundamental tools and webpack to provide development environment and production builds.

**Comment by pakastin** [comment]
Nowadays i just tend to copy redom.min.js from node_modules/redom/dist/redom.min.js to public/js/redom.js and include with script tag before main.js – saves time in bundling phase, and there's nothing wrong going a bit oldskool 😛

**Comment by tamilvendhank-helptap** [comment]
Oh, okay! I do like being old school. That is actually quite the reason why I am alone mostly :-D(among my peers of-course).

Also, I am just coming out of React & I am not going back, unless if I am getting paid very very much only for using React.
I must say, I was looking for ways to use native tools for SPA development. I was taught 10 years ago of a module concept, which I was trying to improve on. It was like your concept, no build tool etc. but modular with individual JavaScript modules & templates. Then I found, Redom. Soon, I began to write components in Redom. Now, I use Redom within the existing React project. I wish, I had found Redom before starting my current project. And, also, I build new projects with Redom(Like I said, I am not going back!)

Anyway, I am curious how you handle images, css etc. If it is fine, could you elaborate on that?  

Traditionally, I'd put all the css files in the main index.html. These days, the applications becomes huge quickly and many times, I'd look for a way to load css files on demand with their respective modules. But, I am still packing them all in one file & load them in index.html.

**Comment by pakastin** [comment]
I use postcss or just oldskool `@import` for CSS, and for images just static files or if I need dynamic stuff I use node.js..

**Comment by pakastin** [comment]
Well, actually you can even use RE:DOM for that 😄:

```js
function import CSS (href) {
  if (cssImport[filename]) return;
  
  mount(document.head, el('link', { rel: 'stylesheet', href }));
}
```

**Comment by tamilvendhank-helptap** [comment]
That is simple & neat! Thanks for that.

**Comment by pakastin** [comment]
Anytime! 🫡
