### ISSUE TITLE
Typescript+type definitions support

### ISSUE THREAD

**Issue by jahan-addison** [redom/redom#78]
Type definitions for this package would be great. Looks like a useful project.

**Comment by pakastin** [comment]
Hi! I don't use types, but I know someone already started adding them to Definitely Typed. Let me check..

**Comment by pakastin** [comment]
The source is really easy to follow as well:
https://github.com/pakastin/redom/tree/master/src
https://github.com/pakastin/redom/tree/master/dist/redom.es.js

**Comment by pakastin** [comment]
@terkelg do I remember correctly that you at least planned about writing type definitions?

**Comment by jens1o** [comment]
Otherwise, I may take a shot if you'd like to.

**Comment by pakastin** [comment]
That would be awesome! 👍

**Comment by jens1o** [comment]
Will check this tomorrow.

**Comment by terkelg** [comment]
I was really close to convert the whole project to Flow, but decided not to anyway

**Comment by pakastin** [comment]
Btw. @jens1o I'd like to keep the source in JavaScript, so type definitions should be on a separate file. It's possible with at least TypeScript, right?

**Comment by pakastin** [comment]
I think JSDoc could actually be the best option..
https://github.com/Microsoft/TypeScript/wiki/JsDoc-support-in-JavaScript

**Comment by pakastin** [comment]
I actually started creating JSDoc comments. You're welcome to participate (I'm such a noob with types 😂):
https://github.com/redom/redom/blob/jsdoc/dist/redom.es.js

**Comment by nikcorg** [comment]
@terkelg I wouldn't get involved with Flow. It seems quite fickle and things keep breaking with version updates. TypeScript would be my recommendation, if you want to add strong typing information.

**Comment by pakastin** [comment]
JSDoc seems good.

**Comment by terkelg** [comment]
@nikcorg Agree, that's what I concluded too. Typings is not even worth it imo, it just adds yet another layer of abstraction and build tools.

**Comment by jens1o** [comment]
Okay, that's a point, and most ides also like it :)

**Comment by pakastin** [comment]
I still think [definitely typed](http://definitelytyped.org) might be the best choice. I'd like to keep the source as clean as possible. I also feel there's not a crucial need for types, since the API is relatively simple (HyperScript being the most complex thing, but even that is fairly standard stuff).

I'm closing this for now because I don't have time for studying definitely typed (we're having our second baby soon 🍼), but if someone would like to contribute by writing definitely typed definitions, that would be great! ❤️

**Comment by pakastin** [comment]
RE:DOM is now definitely typed!
https://www.npmjs.com/package/@types/redom
