### ISSUE TITLE
sample list const is same name as function

### ISSUE THREAD

**Issue by vegarringdal** [redom/redom#80]
Need to update some of the samples, like list function and const have same name
```
import { el, list, mount } from 'redom';

class Li {
  constructor () {
    this.el = el('li');
  }
  update (data) {
    this.el.textContent = data.name;
  }
}

// const cant be same name as function...
const list = list('ul', Li, '_id');



```

**Comment by pakastin** [comment]
Thanks, fixed now! 😎👍

**Comment by vegarringdal** [comment]
@pakastin wasnt the router missing a update too ?

It takes a parent as first arg, thats not what the docs says

**Comment by pakastin** [comment]
Thanks! Here's the doc's source if you'd like to create a PR: https://github.com/redom/redom/blob/master/dist/doc.md

**Comment by pakastin** [comment]
I'm watching the Snowden movie atm, will get back to this tomorrow.. 😎
