### ISSUE TITLE
a tiny DOM NODE.js library ... or also as NO-NODE.js standalone??

### ISSUE THREAD

**Issue by Neohiro79** [redom/redom#83]
import { el, mount } from 'redom';

results in:
Uncaught SyntaxError: Unexpected token import

so is there a "standalone" edition without the whole module f**k ?

**Comment by sloschi** [comment]
this is not a node.js library. if you want to render html serverside, hava a look at [nodom.](https://github.com/redom/nodom)

**Comment by Neohiro79** [comment]
thanx for the quick answer - so I need to use it in conjunction with nodom to be able to use it in a plain vanilla html page to get it to work? I made a simple .html page, included the redom.js and tried the code
in a script.js file - and nothing works (error above), so how do I make "import" work without node.js, is the nodom.js file the right way to handle it?

**Comment by sloschi** [comment]
because of the exception you got, i assumed you used node to execute your script. Obviously, i was mistaken, so lets try this again ;)

if you want to user redom in a browser (aka client side rendering) you have two options:

1. you use the npm package (npm install redom). then you will need to use some kind of web bundler (e.g. webpack) to make it work.

2. You link redom into your html with the script tag. Then you dont need to use "import". When using redom like this, there will be a global object "redom" that you can access.

**Comment by pakastin** [comment]
If you use ES2015 (notice browser support), you can also call:

    const { el, mount } = redom;

Good that you brought this out, because [README used to have a tutorial about this](https://github.com/redom/redom/tree/0bfd4eb23db682658a3f6a11d909deca35e1ba58), but I recently took it away and have forgot to add it to the documentation

**Comment by Neohiro79** [comment]
Superior! That's what I wanted to know. Now I got it to work, simply by
putting both script includes to the bottom (aka body), and I could also see
the global object via console.log(redom); 

It might be important to point that out at least somewhere on the main page,
hence you do not need to use any bundler, npm or node.js whatso-f***ing-ever
and instead use it plain simple like it would be a standalone framework.

Not everyone can study on MIT to make things work ;-))

Thanx for the superior support and quick answers !!

**Comment by pakastin** [comment]
No worries, hope you like RE:DOM! 😉

**Comment by Neohiro79** [comment]
I pretty much guess so ;-)

**Comment by pakastin** [comment]
Perfect! If you have any questions, just raise an issue or join us on Gitter (redom/redom) or [koodiklinikka.slack.com](koodiklinikka.slack.com) (#redom) (get invite at [koodiklinikka.fi](koodiklinikka.fi))

**Comment by Neohiro79** [comment]
I will sure come back with some questions or maybe even suggestions, as soon as I'm able
to dive into the whole topic the next days and weeks, I will get in contact, I tried riot.js and 
vue.js but it seems to complex for a quick tryout, so I found your awesome lib yesterday 
and was falling in love with the simplicity of "calls" available. At least I felt that way,
 so I will see how it works out for me. Best wishes and good luck from germany! :-)

**Comment by pakastin** [comment]
Btw. I'm actually one of riot.js's early contributors 😉

**Comment by Neohiro79** [comment]
nice ... that says it all I guess :-)))

At least it shows that I'm not alone with feeling a bit overdosed from some of those so called super-frameworks ...

**Comment by Neohiro79** [comment]
I will watch your vid on youtube "Minimum Viable View Library", try to get into the topic as soon as I can!

**Comment by pakastin** [comment]
You're most definitely not alone 😄

**Comment by Neohiro79** [comment]
Hello Juha,

Still trying to figure some things out, right now I'm stuck with your router function.
Could you take a closer look on this?

[router-qa.zip](https://github.com/redom/redom/files/1199512/router-qa.zip)

**Comment by pakastin** [comment]
Have you read [the doc](https://redom.js.org/documentation/#router)?

Basically you define "routes" first by creating the router component:

```javascript
this.content = router('.content', { home: Home, about: About, contact: Contact });
```

..and then update the view by defining which View to use:
```javascript
this.content.update('home', data);
```

**Comment by pakastin** [comment]
Here's a working example: https://github.com/pakastin/redom-state/blob/master/js/content/index.js

**Comment by pakastin** [comment]
And here's how router work under the hood:
https://github.com/redom/redom/blob/master/src/router.js

Really simple stuff:

- [If the route is different than last time](https://github.com/redom/redom/blob/master/src/router.js#L15)
  - [Create the View](https://github.com/redom/redom/blob/master/src/router.js#L19)
  - [Set View as the only child](https://github.com/redom/redom/blob/master/src/router.js#L22)

- [Always update (unless no View available)](https://github.com/redom/redom/blob/master/src/router.js#L24)

**Comment by jens1o** [comment]
Question: Is it clever enough to detect things that are same in both views, for example the menu itself and just changes as less as possible?

**Comment by pakastin** [comment]
You could use `initData` for that, but no, not out of the box.

**Comment by pakastin** [comment]
But not even virtual dom can do such a thing

**Comment by pakastin** [comment]
See https://facebook.github.io/react/docs/reconciliation.html

**Comment by Neohiro79** [comment]
I've read the doc, yes, but I cannot figure it out. I don't get it,
why can't there be a provided doc with three links and all 'onclick'
get a different content, something that plain simple should not be
that hard to achieve. What am I missing?

import { Home } from './home'; ???

Regarding the link of your "working example":
Do I have to make a folder named 'home' and inside of it an index.js
or is it a class imported from somewhere?

**Comment by Neohiro79** [comment]
`class Home {
  constructor(){
    this.el = redom.el('p', 'this is the Homepage');   
  }
}  
class About {
  constructor(){
    this.el = redom.el('p', 'this is the Aboutpage');
  }
  update ({ input }) {
    this.el.textContent = input;
  }  
}
class Contact {
  constructor(){
    this.el = redom.el('p', 'this is the contactpage');
  }
  update ({ input }) {
    this.el.textContent = input;
  }  
}



class Content {

  constructor () {

    this.el = redom.el('.content');

    this.router = redom.router(this.el, {
      '': Home,
      about: About,
      contact: Contact
    });
  }
  update (data) {
    const { section } = data;

    this.router.update(section, data);
  }
}

var testC = new Content();`

**Comment by pakastin** [comment]
Another example: https://jsfiddle.net/3079shdy/

**Comment by pakastin** [comment]
Here's the `content` folder structure for the example:
https://github.com/pakastin/redom-state/tree/master/js/content

**Comment by Neohiro79** [comment]
Thanx a lot, that was what I was looking for!

**Comment by Neohiro79** [comment]
One last thing: How do I create a proper link with el() ?

neither el('a', 'link-name') nor el('a href', 'link-name') works,
and how to I specify the target (ie. site-section, other URL, whatever) ?

**Comment by pakastin** [comment]
`el('a', { href: 'https://redom.js.org' }, 'RE:DOM website')` 😉

**Comment by Neohiro79** [comment]
Perfect 👍 👍

**Comment by pakastin** [comment]
You can define both attributes and properties there.. More about that [here](https://redom.js.org/documentation/#attributes-and-properties)
