### ISSUE TITLE
[Question] List.update doesn't work correctly?

### ISSUE THREAD

**Issue by MrSorcus** [redom/redom#84]
Hi, can you help please?
https://gist.github.com/MrSorcus/093e3b1e54a49ea8ef7110825a780665 - simple todo.
Steps:
1. Add three elements. For example - 1, 2, 3
2. Click on "X" for deleting first element.
3. Third element will be deleted.

Why?

**Comment by pakastin** [comment]
You use a single _re where you basically save every item (so that only the last one is there in the update round).

Please see: https://redom.js.org/documentation/#components

**Comment by sloschi** [comment]
This is probably no problem with redom, but with your understanding of javascript ;)

indexOf returns -1 if an item is not found. splice(-1, 1) removes the last element in an array. perhaps that could be the reason? Try to debug line 23 in your code, and see what indexOf returns.

**Comment by MrSorcus** [comment]
https://gist.github.com/MrSorcus/093e3b1e54a49ea8ef7110825a780665
Sorry, i'm doing something wrong, but what?

**Comment by pakastin** [comment]
I get back to you after couple of hours.. 😉

**Comment by pakastin** [comment]
Sorry it took me so long, but here's an example: https://gist.github.com/pakastin/8300be5c8e1e280e2a41e4d2a769811b

Even better would be to separate data handling and view logic, but that's another story :)

**Comment by pakastin** [comment]
Here's another example:
https://github.com/pakastin/redom-state

(see https://pakastin.github.io/redom-state/#fiddle and https://github.com/pakastin/redom-state/blob/master/js/actions.js)

😉

**Comment by MrSorcus** [comment]
Thank you so much.

**Comment by MrSorcus** [comment]
> Even better would be to separate data handling and view logic, but that's another story 😎

Where can i read about this? Thank you.
