### ISSUE TITLE
New question about List.update.

### ISSUE THREAD

**Issue by MrSorcus** [redom/redom#85]
https://gist.github.com/MrSorcus/7f6fc5140360be0903f935173fce70de
and
http://todomvc.com/examples/angularjs/ (Here used Angular 1.X)

Steps to reproduce (for both links):
1. Add five elements (1, 2, 3, 4, 5)
2. Tap checkbox on element 3
3. Remove first element.
4. Element 4 blinking.

I understand why it's blinking (maybe), but i think that is not normal.
Angular 1.X has similar behavior, but not Angular 2.X (http://todomvc.com/examples/angular2/) or React (http://todomvc.com/examples/react/) or any other.
Is it possible to fix it? Thank you.

**Comment by MrSorcus** [comment]
Up...

**Comment by pakastin** [comment]
Check out `keyed list` section in docs: https://redom.js.org/documentation/#keyed-list

You should add the third parameter when creating the list to define some kind of id to identify items.. With angular it's `track by` and with react it's the `key` attribute.

https://docs.angularjs.org/api/ng/directive/ngRepeat
https://facebook.github.io/react/docs/lists-and-keys.html

**Comment by MrSorcus** [comment]
Oh, thank you again.

**Comment by pakastin** [comment]
No worries 😉

**Comment by leeoniya** [comment]
@pakastin the way `help wanted` labels are traditionally used is to solicit contributions. issues like this typically get labeled `discussion` or `question`. in my experience anyway.

**Comment by pakastin** [comment]
Oh, didn’t know about that – thanks for letting know! I thought it means someone needs help 😂

**Comment by pakastin** [comment]
Changed now 👌
