### ISSUE TITLE
Extend place with el().

### ISSUE THREAD

**Issue by MrSorcus** [redom/redom#87]
Something like this:
```Javascript
this.el = el("div",
	this.show = place(
		this.p_element = el("p", "Show me after 3 seconds")
	)
);

mount(document.body, this.el);

setTimeout(() => {
	this.show.update(true);
}, 3000);

setTimeout(() => {
	this.p_element.textContent = "Hello World!";
}, 5000);
```

Here commit (but is not a good solution(i'm not sure...), only for example) - https://github.com/MrSorcus/redom/commit/7ab27461ec0f9877d18231e30eb79b855ff91f20
What do you think? Thank you.

**Comment by MrSorcus** [comment]
Up.

**Comment by pakastin** [comment]
I thought about including support for element, but the main use case is the components (views). You can remove element from the DOM just by setting it's CSS `el.style.display = 'none'` and back by setting `el.style.display = ''`..

**Comment by pakastin** [comment]
Good example of a use case is when you have a large part of application which you need to construct/update/destroy easily..

**Comment by MrSorcus** [comment]
Maybe separate `place` for `elements` & `components`?

**Comment by MrSorcus** [comment]
Close issue or not?

**Comment by pakastin** [comment]
I'll get back to you, been busy

**Comment by MrSorcus** [comment]
Ok, sorry.

**Comment by MrSorcus** [comment]
:-)

**Comment by pakastin** [comment]
I still feel place's responsibility is to create, update and destroy components on-demand.. Closing now.
