### ISSUE TITLE
[Question] Updated elements - diff

### ISSUE THREAD

**Issue by luwes** [redom/redom#89]
Thanks for this great UI library. 

One thing I was wondering, lets say you have a component with a lot of props like `{title}`, `{description}`, `{images}` which holds multiple `{image}` which in turn holds `{caption}`, `{src}`, etc. and say one prop in that image changes. Maybe the src of the 2nd image. You do an update on that component.

Is only that specific src attribute being reset or will the whole component be re-rendered?

From the examples I can tell it seems up to the developer to write logic for this in the `update` function but is there an easy way to only have the specific tags and attributes be targeted?

**Comment by luwes** [comment]
Found the diffing part in the Docs :)

**Comment by pakastin** [comment]
Perfect! 👌
Btw, you can join us in [Gitter](http://gitter.im/redom/redom) 😉
