### ISSUE TITLE
svg on mobile

### ISSUE THREAD

**Issue by gblok** [redom/redom#94]
svg not visible on mobile,
tested on android/chrome 42

[demo](https://jsfiddle.net/gblok/2k73wx2L/50/)

**Comment by pakastin** [comment]
There's SVG inside HTML inside SVG, that might be the issue. Desktop somehow renders HTML inside SVG, but mobile doesn't.

**Comment by pakastin** [comment]
```
body
  svg
    #root
      main
      section
        svg
```

**Comment by pakastin** [comment]
If you really need HTML inside SVG, you should use [`<foreignObject>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject), but better just not..

**Comment by pakastin** [comment]
Oh sorry, my mistake – let's see now..

**Comment by pakastin** [comment]
Could this be the reason: https://stackoverflow.com/a/43962207

**Comment by gblok** [comment]
How fix is it? may by reason make fallback to xlink:href?

**Comment by pakastin** [comment]
`setAttributeNS(’xlink:href’, ns);`

**Comment by pakastin** [comment]
I’m adding a shortcut to SVG ns inside RE:DOM as convenience, just a moment..

**Comment by pakastin** [comment]
You can now use (since v:
```
import { s } from 'redom';

const use = s('use');

use.setAttributeNS('xlink:href', '#menu', s.ns);
```

https://github.com/redom/redom/releases/tag/v3.8.2

**Comment by pakastin** [comment]
I was thinking should I add `s('use', { xlink: { href: '#menu' } })` as a convenience..

**Comment by pakastin** [comment]
I'm pretty sure there's no `xlink` attribute, so it should be safe to use..

**Comment by pakastin** [comment]
You can now use `s('use', { xlink: { href: '#menu' } })` (since [v3.8.3](https://github.com/redom/redom/releases/tag/v3.8.3)) 😉
