### ISSUE TITLE
No mount events when mounting into Shadow DOM

### ISSUE THREAD

**Issue by perry-mitchell** [redom/redom#95]
Hi!

Love this library. Found a little quirk though today.. I've been using ShadowRoots to create safe containers for styles etc, and have been using Redom to populate the root with elements (which works fine):

```javascript
const myRootEl = document.createElement("div");
const myRoot = myRootEl.createShadowRoot();

function MyCustomElement() {
  this.el = el("div", "Hello there");
  this.onmount = function() {
    console.log("Mounted..");
  }
}

const myElement = new MyCustomElement();
mount(myRoot, myElement);
```

In my example ^, "Mounted.." is never logged. If I were to change the mount line to `mount(myRootEl, myElement)` (so that it mounts to a "real" element), the log comes.

This problem may become more prevalent as the Shadow DOM API is implemented by more browsers, but it has been in Chrome for some time. Are there any plans to fix this? Would you accept a PR if you're too busy?

**Comment by pakastin** [comment]
Hmm.. I think the issue is here:
https://github.com/redom/redom/blob/2051da55600538c055de00517eb852f54e636b7f/src/mount.js#L78

Shadow root is not `Document`, right?

**Comment by pakastin** [comment]
Too bad MDN is down at the moment :D Do you know how to detect if an element is in the shadow DOM?

**Comment by pakastin** [comment]
Hmm.. `instanceof ShadowRoot` –> should be an easy fix!

**Comment by pakastin** [comment]
Is it enough to know that the element have been mounted to `ShadowRoot` or should we (could we?) know the ShadowRoot is mounted to it's parent as well?

**Comment by perry-mitchell** [comment]
For me it seems to break on this like: `if (remount || (!triggered && (traverse && traverse.__redom_mounted))) {`:

https://github.com/redom/redom/blob/2051da55600538c055de00517eb852f54e636b7f/src/mount.js#L61

Seems like the `__redom_mounted` property isn't able to be set on the Shadow Root. Seems kind of problematic due to the fact that this is used for tracking the mount status (so it seems) on each element..

**Comment by pakastin** [comment]
Yeah, that should be set after the if I showed you.. I have a fix almost ready ;)

**Comment by perry-mitchell** [comment]
> I have a fix almost ready ;)

That'd be incredible!

I'm playing with the ShadowRoot elements a lot in Chrome, and they just generally seem to act weirdly when compared to regular elements (parent element is always `null` for instance).

**Comment by pakastin** [comment]
If it's fine that `onmount` triggers when an element is attached to a shadow root?

**Comment by pakastin** [comment]
Yeah, shadow root is a separate browser instance, so I think it's impossible to know it's parent.

**Comment by perry-mitchell** [comment]
> If it's fine that onmount triggers when an element is attached to a shadow root?

Yes, that sounds fine. I think it should do that imo.

> Yeah, shadow root is a separate browser instance, so I think it's impossible to know it's parent.

Ah, fair enough..

**Comment by pakastin** [comment]
Could you try out: https://github.com/redom/redom/tree/shadow-root

At least it's passing my simple test now:
https://github.com/redom/redom/blob/c14b4b7689333452cecb283f1fccd933a1c76074/test/test.js#L178-L194 ;)

**Comment by pakastin** [comment]
Build is here: https://github.com/redom/redom/blob/shadow-root/dist/redom.min.js

**Comment by pakastin** [comment]
Added `unmount` test as well..passes! 👍

**Comment by perry-mitchell** [comment]
It WORKS! Thanks so much, that was incredibly fast!

**Comment by pakastin** [comment]
Ok, shouldn't break anything, so I just publish that immediately :)

**Comment by perry-mitchell** [comment]
I owe you a beer/coffee/beverage if I ever catch you at a conference (I'm in Helsinki). I don't think I've seen an issue solved so quickly.

> Ok, shouldn't break anything, so I just publish that immediately :)

That'd be a huge help..

**Comment by pakastin** [comment]
I added memoization as well https://github.com/redom/redom/blob/shadow-root/src/mount.js#L5

**Comment by pakastin** [comment]
> I owe you a beer/coffee/beverage if I ever catch you at a conference
Hey no worries, glad you like RE:DOM! 😎

**Comment by pakastin** [comment]
It's good to have shadow DOM support :)

**Comment by pakastin** [comment]
Released! 💪 Thanks for letting know about the issue ❤️
https://github.com/redom/redom/releases/tag/v3.8.8

**Comment by perry-mitchell** [comment]
Happy to help, but you did the work. Cheers!

**Comment by pakastin** [comment]
Haha, and [Travis](https://travis-ci.org/redom/redom?branch=master) passed 😅

**Comment by pakastin** [comment]
> I don't think I've seen an issue solved so quickly.

Well, RE:DOM is [one of the fastest](http://www.stefankrause.net/wp/?p=454) view libraries out there – in every way 😆
