### ISSUE TITLE
Provide attributes when creating a list

### ISSUE THREAD

**Issue by ErikWittern** [redom/redom#97]
I would love to be able to (optionally, as can be done in `el`) provide attributes when creating a list, e.g., like so:

```javascript
const ul = list('ul', {class: 'ul-styling'}, Li);
```

Is there a way to do this?

**Comment by pakastin** [comment]
Yeah, it’s possible:

`const ul = list(el('ul', {class: 'ul-styling'}), Li);`

😉

**Comment by ErikWittern** [comment]
Hi @pakastin, thank you for pointing out that this *does* work as expected. And for your great work on RE:DOM in general, of course!

I was put off by an error thrown by TypeScript:
![image](https://user-images.githubusercontent.com/1745998/33799881-205d5fb4-dd02-11e7-94d5-a1e5f2e1c658.png)
The error states:
```
[ts]
Argument of type '{ class: string; }' is not assignable to parameter of type 'RedomComponentConstructor'.
  Object literal may only specify known properties, and 'class' does not exist in type 'RedomComponentConstructor'.
```

I guess the TypeScript definition may be wrong or outdated?! I use RE:DOM version `3.8.8`, but the definitions are at `^3.6.0`.

In any case, thank you for the prompt reply. I will close this (non-) issue.

**Comment by pakastin** [comment]
Oh sorry, yeah you can't put attributes/properties straight to the `list` factory (or `List` constructor). Valid arguments are here: https://redom.js.org/documentation/#lists

If you need more complex parent element/component child element/component, please use the reference instead..

It's also possible to make a custom `list` ;)

**Comment by pakastin** [comment]
You can for example `extend` from `List` (`import { List } from 'redom';`)

**Comment by pakastin** [comment]
https://github.com/redom/redom/blob/master/src/list.js
